apiVersion: v1
kind: Namespace
metadata:
  name: linkwarden

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: linkwarden-config
  namespace: linkwarden
data:
  NEXTAUTH_SECRET: "BfNy5jw3Jak7ZRWPZsfPgfEhEkagcNHJv5F4raNqD3t2XTL9w3CyRCRJ9C9e5237"
  NEXTAUTH_URL: "https://weblink.likongkong.top/api/v1/auth"
  POSTGRES_PASSWORD: "J9haSdufU84TPi63wSzvUzJg3GK6Awm7w8E7zrBGJRFe8ur6Ltqenu9Q7uTGJsnR"
  DATABASE_URL: "postgresql://postgres:J9haSdufU84TPi63wSzvUzJg3GK6Awm7w8E7zrBGJRFe8ur6Ltqenu9Q7uTGJsnR@postgres:5432/postgres"
  # 用于禁止注册控制，默认先填false，部署完成注册账号后再修改成true禁止注册
  NEXT_PUBLIC_DISABLE_REGISTRATION: "false"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: linkwarden
  labels:
    app: linkwarden
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: linkwarden-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: linkwarden
  labels:
    app: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linkwarden
  namespace: linkwarden
  labels:
    app: linkwarden
spec:
  serviceName: "linkwarden"
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:latest
          envFrom:
            - configMapRef:
                name: linkwarden-config
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /data/data
              name: linkwarden-data
      volumes:
        - name: linkwarden-data
          persistentVolumeClaim:
            claimName: linkwarden-data-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data-pvc
  namespace: linkwarden
  labels:
    app: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: linkwarden
  labels:
    app: linkwarden
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden
  namespace: linkwarden
  labels:
    app: linkwarden
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32006
  selector:
    app: linkwarden



