apiVersion: v1
kind: Namespace
metadata:
  name: next-terminal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: next-terminal-pvc
  namespace: next-terminal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-terminal
  namespace: next-terminal
  labels:
    app: next-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-terminal
  template:
    metadata:
      labels:
        app: next-terminal
    spec:
      containers:
      - name: guacd
        image: dushixiang/guacd:latest
        volumeMounts:
        - name: data-volume
          mountPath: /usr/local/next-terminal/data
      - name: next-terminal
        image: dushixiang/next-terminal:latest
        env:
        - name: DB
          value: "sqlite"
        - name: GUACD_HOSTNAME
          value: "localhost"
        - name: GUACD_PORT
          value: "4822"
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: data-volume
          mountPath: /usr/local/next-terminal/data
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: data-volume
        persistentVolumeClaim:
          claimName: next-terminal-pvc
      

---
apiVersion: v1
kind: Service
metadata:
  name: next-terminal
  namespace: next-terminal
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
    nodePort: 30001
  selector:
    app: next-terminal