services:
  code-server:
    container_name: code-server
    ports:
        - 8080:8080
    volumes:
        - /root/codeserver/.local:/home/coder/.local
        - /root/codeserver/.config:/home/coder/.config
        - /root/codeserver/code:/home/coder/project
    user: 0:0
    environment:
        - DOCKER_USER=root
    image: codercom/code-server:latest
    networks:
        - tunnel
networks:
  tunnel:
    external: true