services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - tunnel

networks:
  tunnel:
    external: true

volumes:
  uptime-kuma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.55,rw
      device: ":/mnt/datashare/dockerdata/uptime-kuma"